/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html", "./js/**/*.js"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#e2e2e2",
        "surface-container-lowest": "#0e0e0e",
        "inverse-on-surface": "#313030",
        "surface": "#131313",
        "primary-container": "#e2e2e2",
        "on-secondary-container": "#00311f",
        "secondary-fixed": "#6ffbbe",
        "outline-variant": "#444748",
        "on-error": "#690005",
        "on-tertiary": "#1000a9",
        "text-muted": "#A3A3A3",
        "surface-container-highest": "#353534",
        "on-surface-variant": "#c4c7c8",
        "surface-tint": "#c6c6c7",
        "accent-green-glass": "rgba(16, 185, 129, 0.1)",
        "surface-container-high": "#2a2a2a",
        "on-surface": "#e5e2e1",
        "error": "#ffb4ab",
        "secondary-container": "#00a572",
        "on-secondary": "#003824",
        "on-primary-fixed": "#1a1c1c",
        "tertiary-container": "#e1e0ff",
        "tertiary": "#ffffff",
        "on-primary-container": "#636565",
        "on-tertiary-container": "#4f51dd",
        "on-tertiary-fixed": "#07006c",
        "secondary-fixed-dim": "#4edea3",
        "primary-fixed-dim": "#c6c6c7",
        "secondary": "#4edea3",
        "secondary-alt": "#00E699",
        "on-secondary-fixed-variant": "#005236",
        "on-primary-fixed-variant": "#454747",
        "surface-container": "#201f1f",
        "surface-bright": "#3a3939",
        "surface-dim": "#131313",
        "surface-elevated": "#171717",
        "on-primary": "#2f3131",
        "tertiary-fixed": "#e1e0ff",
        "tertiary-fixed-dim": "#c0c1ff",
        "surface-container-low": "#1c1b1b",
        "on-background": "#e5e2e1",
        "outline": "#8e9192",
        "surface-variant": "#353534",
        "primary": "#ffffff",
        "inverse-surface": "#e5e2e1",
        "error-container": "#93000a",
        "inverse-primary": "#5d5f5f",
        "background": "#131313",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "on-secondary-fixed": "#002113",
        "on-error-container": "#ffdad6",
        "border-subtle": "#262626"
      },
      borderRadius: {
        "DEFAULT": "1px",
        "sm": "1px",
        "md": "2px",
        "lg": "2px",
        "xl": "2px",
        "2xl": "2px",
        "3xl": "2px",
        "full": "9999px"
      },
      spacing: {
        "margin-safe": "32px",
        "stack-gap": "16px",
        "grid-columns": "12",
        "gutter": "24px",
        "section-v-md": "80px",
        "section-v-lg": "120px"
      },
      fontFamily: {
        "table-data": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "display-hero": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"]
      },
      fontSize: {
        "table-data": ["14px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "headline-lg": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "label-mono": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "display-hero": ["72px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "600" }],
        "headline-md": ["32px", { "lineHeight": "1.3", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-lg": ["20px", { "lineHeight": "1.6", "fontWeight": "400" }]
      }
    }
  },
  plugins: []
}
